### ISSUE TITLE
Make non-stream chat max_tokens smaller

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/bigdl-llm-tutorial#54]
Otherwise may wait for a long time to get the result, not friendly for demonstration.

**Comment by Ariadne330** [comment]
In `3_BasicApp.ipynb` the `max_new_tokens` number is 32;
In `4_1_ChatGLM2-6B.ipynb` the `max_new_tokens` number is 128 (for **`generate`** ,`stream-chat` and **`langchain`**);
In `4_2_Baichuan-13B.ipynb` the `max_new_tokens` number is **128**;
In `5_1_ChatBot.ipynb` for stream-chat number is 128;
And in Chapter 6 and 7 the number returns to 32

Maybe the parameters in 4_1 `generate` and `langchain` API, 4_2 the number should be smaller.
